import { FC } from "react";

const Home: FC = () => {
  return (
    <div className="bg-slate-400">
      <p>sssss111</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>sssss</p>
      <p>ssssslastttt</p>
    </div>
  );
};

export default Home;
